### PR TITLE
Fix snapshot of runtime nerdctl

### LINKED ISSUE #100: Failing `kwokctl snapshot` with runtime `nerdctl`
### Which jobs are failing?

https://github.com/kubernetes-sigs/kwok/blob/88e598265a3c899bfb010088d8a6d85ebf429a57/.github/workflows/test.yaml#L137-L141

### Which tests are failing?

https://github.com/kubernetes-sigs/kwok/actions/runs/3565851048/jobs/5991537840

``` console
================================================================================
Testing kwokctl/kwokctl_nerdctl_snapshot...
github.com/docker/buildx 0.[9](https://github.com/kubernetes-sigs/kwok/actions/runs/3565851048/jobs/5991537840#step:13:10).1+azure-2 ed00243a0ce2a0aee75311b06e32d33b44729689
mkdir: cannot create directory ‘tmp’: File exists
unpacking docker.io/local/kwok:test (sha256:5019cea8f3dd71453e676622dd7825d12c2e7ae4272560aa295d7787dfbf0245)...
Loaded image: docker.io/local/kwok:testTest snapshot on nerdctl for 1.25.3 1.24.7 1.23.13 1.22.15 1.21.14 1.20.15
------------------------------
Testing snapshot on nerdctl for 1.25.3
{"time":"2022-11-28T14:50:53.869177459Z","level":"INFO","source":"/home/runner/work/kwok/kwok/pkg/kwokctl/cmd/create/cluster/cluster.go:75","msg":"Creating cluster","cluster":"snapshot-cluster-nerdctl-1-25-3"}
{"time":"2022-11-28T14:50:54.550340799Z","level":"INFO","source":"/home/runner/work/kwok/kwok/pkg/kwokctl/cmd/create/cluster/cluster.go:75","msg":"Starting cluster","cluster":"snapshot-cluster-nerdctl-1-25-3"}
time="2022-11-28T14:50:54Z" level=info msg="Creating network kwok-snapshot-cluster-nerdctl-1-25-3"
time="2022-11-28T14:50:54Z" level=warning msg="Ignoring: service kube_apiserver: [Links]"
time="2022-11-28T14:50:54Z" level=warning msg="Ignoring: volume: Bind: [CreateHostPath]"
time="2022-11-28T14:50:54Z" level=warning msg="Ignoring: volume: Bind: [CreateHostPath]"
time="2022-11-28T14:50:54Z" level=warning msg="Ignoring: volume: Bind: [CreateHostPath]"
time="2022-11-28T14:50:54Z" level=warning msg="Ignoring: service kwok_controller: [Links]"
time="2022-11-28T14:50:54Z" level=warning msg="Ignoring: volume: Bind: [CreateHostPath]"
time="2022-11-28T14:50:54Z" level=warning msg="Ignoring: volume: Bind: [CreateHostPath]"
time="2022-11-28T14:50:54Z" level=warning msg="Ignoring: volume: Bind: [CreateHostPath]"
time="2022-11-28T14:50:54Z" level=warning msg="Ignoring: volume: Bind: [CreateHostPath]"
time="2022-11-28T14:50:54Z" level=warning msg="Ignoring: service kube_controller_manager: [Links]"
time="2022-11-28T14:50:54Z" level=warning msg="Ignoring: volume: Bind: [CreateHostPath]"
time="2022-11-28T14:50:54Z" level=warning msg="Ignoring: volume: Bind: [CreateHostPath]"
time="2022-11-28T14:50:54Z" level=warning msg="Ignoring: volume: Bind: [CreateHostPath]"
time="2022-11-28T14:50:54Z" level=warning msg="Ignoring: volume: Bind: [CreateHostPath]"
time="2022-11-28T14:50:54Z" level=warning msg="Ignoring: service kube_scheduler: [Links]"
time="2022-11-28T14:50:54Z" level=warning msg="Ignoring: volume: Bind: [CreateHostPath]"
time="2022-11-28T14:50:54Z" level=warning msg="Ignoring: volume: Bind: [CreateHostPath]"
time="2022-11-28T14:50:54Z" level=warning msg="Ignoring: volume: Bind: [CreateHostPath]"
time="2022-11-28T14:50:54Z" level=warning msg="Ignoring: volume: Bind: [CreateHostPath]"
time="2022-11-28T14:50:54Z" level=info msg="Ensuring image registry.k8s.io/etcd:3.5.6-0"
time="2022-11-28T14:50:54Z" level=info msg="Ensuring image registry.k8s.io/kube-apiserver:v1.25.3"
time="2022-11-28T14:50:54Z" level=info msg="Ensuring image local/kwok:test"
time="2022-11-28T14:50:54Z" level=info msg="Ensuring image registry.k8s.io/kube-controller-manager:v1.25.3"
time="2022-11-28T14:50:54Z" level=info msg="Ensuring image registry.k8s.io/kube-scheduler:v1.25.3"
time="2022-11-28T14:50:54Z" level=info msg="Creating container kwok-snapshot-cluster-nerdctl-1-25-3-kwok-controller"
time="2022-11-28T14:50:54Z" level=info msg="Creating container kwok-snapshot-cluster-nerdctl-1-25-3-kube-scheduler"
time="2022-11-28T14:50:54Z" level=info msg="Creating container kwok-snapshot-cluster-nerdctl-1-25-3-etcd"
time="2022-11-28T14:50:54Z" level=info msg="Creating container kwok-snapshot-cluster-nerdctl-1-25-3-kube-controller-manager"
time="2022-11-28T14:50:54Z" level=info msg="Creating container kwok-snapshot-cluster-nerdctl-1-25-3-kube-apiserver"
You can now use your cluster with:
{"time":"2022-11-28T14:50:59.168789831Z","level":"INFO","source":"/home/runner/work/kwok/kwok/pkg/kwokctl/cmd/create/cluster/cluster.go:75","msg":"Cluster is ready","cluster":"snapshot-cluster-nerdctl-1-25-3"}

    kubectl config use-context kwok-snapshot-cluster-nerdctl-1-25-3

Thanks for using kwok!
No resources found
No resources found
deployment.apps/fake-pod created
node/fake-node created
Download https://github.com/etcd-io/etcd/releases/download/v3.5.6/etcd-v3.5.6-linux-amd64.tar.gz
{"time":"2022-11-28T14:51:37.882622576Z","level":"ERROR","source":"/opt/hostedtoolcache/go/1.19.3/x64/src/runtime/proc.go:250","msg":"Execute exit","err":"nerdctl cp /home/runner/.kwok/clusters/snapshot-cluster-nerdctl-1-25-3/etcd-data kwok-snapshot-cluster-nerdctl-1-25-3-etcd:/: exit status 1\ntime=\"2022-11-28T14:51:37Z\" level=warning msg=\"failed to inspect NetNS\" error=\"failed to Statfs \\\"/proc/14518/ns/net\\\": no such file or directory\" id=2af2754d12fd763d179bf1e3225b62a7ea3d5a86a37eabc1bb29944a04c8ce85\ntime=\"2022-11-28T14:51:37Z\" level=fatal msg=\"expected container status running, got stopped\"\n"}
Error: Empty snapshot restore failed
Expected: 
Actual: NAMESPACE NAME
default fake-pod-78f5b8f676-gj6r9
NAME
fake-node
{"time":"2022-11-28T14:52:34.878035422Z","level":"INFO","source":"/home/runner/work/kwok/kwok/pkg/kwokctl/cmd/delete/cluster/cluster.go:45","msg":"Stopping cluster","cluster":"snapshot-cluster-nerdctl-1-25-3"}
time="2022-11-28T14:52:34Z" level=info msg="Removing container kwok-snapshot-cluster-nerdctl-1-25-3-kube-scheduler"
time="2022-11-28T14:52:35Z" level=info msg="Removing container kwok-snapshot-cluster-nerdctl-1-25-3-kube-controller-manager"
time="2022-11-28T14:52:35Z" level=info msg="Removing container kwok-snapshot-cluster-nerdctl-1-25-3-kwok-controller"
time="2022-11-28T14:52:35Z" level=info msg="Removing container kwok-snapshot-cluster-nerdctl-1-25-3-kube-apiserver"
time="2022-11-28T14:52:35Z" level=info msg="Removing container kwok-snapshot-cluster-nerdctl-1-25-3-etcd"
time="2022-11-28T14:52:35Z" level=info msg="Removing network kwok-snapshot-cluster-nerdctl-1-25-3"
{"time":"2022-11-28T14:52:35.731964445Z","level":"INFO","source":"/home/runner/work/kwok/kwok/pkg/kwokctl/cmd/delete/cluster/cluster.go:45","msg":"Deleting cluster","cluster":"snapshot-cluster-nerdctl-1-25-3"}
{"time":"2022-11-28T14:52:35.882827316Z","level":"INFO","source":"/home/runner/work/kwok/kwok/pkg/kwokctl/cmd/delete/cluster/cluster.go:45","msg":"Cluster deleted","cluster":"snapshot-cluster-nerdctl-1-25-3"}
------------------------------
Testing snapshot on nerdctl for 1.24.7
{"time":"2022-11-28T14:52:35.899447477Z","level":"INFO","source":"/home/runner/work/kwok/kwok/pkg/kwokctl/cmd/create/cluster/cluster.go:75","msg":"Creating cluster","cluster":"snapshot-cluster-nerdctl-1-24-7"}
{"time":"2022-11-28T14:52:37.003300129Z","level":"INFO","source":"/home/runner/work/kwok/kwok/pkg/kwokctl/cmd/create/cluster/cluster.go:75","msg":"Starting cluster","cluster":"snapshot-cluster-nerdctl-1-24-7"}
time="2022-11-28T14:52:37Z" level=info msg="Creating network kwok-snapshot-cluster-nerdctl-1-24-7"
time="2022-11-28T14:52:37Z" level=warning msg="Ignoring: service kube_apiserver: [Links]"
time="2022-11-28T14:52:37Z" level=warning msg="Ignoring: volume: Bind: [CreateHostPath]"
time="2022-11-28T14:52:37Z" level=warning msg="Ignoring: volume: Bind: [CreateHostPath]"
time="2022-11-28T14:52:37Z" level=warning msg="Ignoring: volume: Bind: [CreateHostPath]"
time="2022-11-28T14:52:37Z" level=warning msg="Ignoring: service kube_controller_manager: [Links]"
time="2022-11-28T14:52:37Z" level=warning msg="Ignoring: volume: Bind: [CreateHostPath]"
time="2022-11-28T14:52:37Z" level=warning msg="Ignoring: volume: Bind: [CreateHostPath]"
time="2022-11-28T14:52:37Z" level=warning msg="Ignoring: volume: Bind: [CreateHostPath]"
time="2022-11-28T14:52:37Z" level=warning msg="Ignoring: volume: Bind: [CreateHostPath]"
time="2022-11-28T14:52:37Z" level=warning msg="Ignoring: service kube_scheduler: [Links]"
time="2022-11-28T14:52:37Z" level=warning msg="Ignoring: volume: Bind: [CreateHostPath]"
time="2022-11-28T14:52:37Z" level=warning msg="Ignoring: volume: Bind: [CreateHostPath]"
time="2022-11-28T14:52:37Z" level=warning msg="Ignoring: volume: Bind: [CreateHostPath]"
time="2022-11-28T14:52:37Z" level=warning msg="Ignoring: volume: Bind: [CreateHostPath]"
time="2022-11-28T14:52:37Z" level=warning msg="Ignoring: service kwok_controller: [Links]"
time="2022-11-28T14:52:37Z" level=warning msg="Ignoring: volume: Bind: [CreateHostPath]"
time="2022-11-28T14:52:37Z" level=warning msg="Ignoring: volume: Bind: [CreateHostPath]"
time="2022-11-28T14:52:37Z" level=warning msg="Ignoring: volume: Bind: [CreateHostPath]"
time="2022-11-28T14:52:37Z" level=warning msg="Ignoring: volume: Bind: [CreateHostPath]"
time="2022-11-28T14:52:37Z" level=info msg="Ensuring image registry.k8s.io/etcd:3.5.6-0"
time="2022-11-28T14:52:37Z" level=info msg="Ensuring image registry.k8s.io/kube-apiserver:v1.24.7"
time="2022-11-28T14:52:37Z" level=info msg="Ensuring image registry.k8s.io/kube-controller-manager:v1.24.7"
time="2022-11-28T14:52:37Z" level=info msg="Ensuring image registry.k8s.io/kube-scheduler:v1.24.7"
time="2022-11-28T14:52:37Z" level=info msg="Ensuring image local/kwok:test"
time="2022-11-28T14:52:37Z" level=info msg="Creating container kwok-snapshot-cluster-nerdctl-1-24-7-kube-scheduler"
time="2022-11-28T14:52:37Z" level=info msg="Creating container kwok-snapshot-cluster-nerdctl-1-24-7-kube-controller-manager"
time="2022-11-28T14:52:37Z" level=info msg="Creating container kwok-snapshot-cluster-nerdctl-1-24-7-etcd"
time="2022-11-28T14:52:37Z" level=info msg="Creating container kwok-snapshot-cluster-nerdctl-1-24-7-kwok-controller"
time="2022-11-28T14:52:37Z" level=info msg="Creating container kwok-snapshot-cluster-nerdctl-1-24-7-kube-apiserver"
You can now use your cluster with:
{"time":"2022-11-28T14:52:41.660050875Z","level":"INFO","source":"/home/runner/work/kwok/kwok/pkg/kwokctl/cmd/create/cluster/cluster.go:75","msg":"Cluster is ready","cluster":"snapshot-cluster-nerdctl-1-24-7"}

    kubectl config use-context kwok-snapshot-cluster-nerdctl-1-24-7

Thanks for using kwok!
No resources found
No resources found
deployment.apps/fake-pod created
node/fake-node created
{"time":"2022-11-28T14:53:19.502931142Z","level":"ERROR","source":"/opt/hostedtoolcache/go/1.19.3/x64/src/runtime/proc.go:250","msg":"Execute exit","err":"nerdctl cp /home/runner/.kwok/clusters/snapshot-cluster-nerdctl-1-24-7/etcd-data kwok-snapshot-cluster-nerdctl-1-24-7-etcd:/: exit status 1\ntime=\"2022-11-28T14:53:19Z\" level=warning msg=\"failed to inspect NetNS\" error=\"failed to Statfs \\\"/proc/18073/ns/net\\\": no such file or directory\" id=4fb042bd8586bcd039dac994d5262e857ed2631ddcc8509367aa5ac50201a179\ntime=\"2022-11-28T14:53:19Z\" level=fatal msg=\"expected container status running, got stopped\"\n"}
Error: Empty snapshot restore failed
Expected: 
Actual: NAMESPACE NAME
default fake-pod-6f5fffcbc-hff5p
NAME
fake-node
{"time":"2022-11-28T14:54:16.753867524Z","level":"INFO","source":"/home/runner/work/kwok/kwok/pkg/kwokctl/cmd/delete/cluster/cluster.go:45","msg":"Stopping cluster","cluster":"snapshot-cluster-nerdctl-1-24-7"}
time="2022-11-28T14:54:16Z" level=info msg="Removing container kwok-snapshot-cluster-nerdctl-1-24-7-kwok-controller"
time="2022-11-28T14:54:16Z" level=info msg="Removing container kwok-snapshot-cluster-nerdctl-1-24-7-kube-scheduler"
time="2022-11-28T14:54:17Z" level=info msg="Removing container kwok-snapshot-cluster-nerdctl-1-24-7-kube-controller-manager"
time="2022-11-28T14:54:17Z" level=info msg="Removing container kwok-snapshot-cluster-nerdctl-1-24-7-kube-apiserver"
time="2022-11-28T14:54:17Z" level=info msg="Removing container kwok-snapshot-cluster-nerdctl-1-24-7-etcd"
time="2022-11-28T14:54:17Z" level=info msg="Removing network kwok-snapshot-cluster-nerdctl-1-24-7"
{"time":"2022-11-28T14:54:17.535599245Z","level":"INFO","source":"/home/runner/work/kwok/kwok/pkg/kwokctl/cmd/delete/cluster/cluster.go:45","msg":"Deleting cluster","cluster":"snapshot-cluster-nerdctl-1-24-7"}
{"time":"2022-11-28T14:54:17.677782486Z","level":"INFO","source":"/home/runner/work/kwok/kwok/pkg/kwokctl/cmd/delete/cluster/cluster.go:45","msg":"Cluster deleted","cluster":"snapshot-cluster-nerdctl-1-24-7"}
------------------------------
Testing snapshot on nerdctl for 1.23.13
{"time":"2022-11-28T14:54:17.692811822Z","level":"INFO","source":"/home/runner/work/kwok/kwok/pkg/kwokctl/cmd/create/cluster/cluster.go:75","msg":"Creating cluster","cluster":"snapshot-cluster-nerdctl-1-23-13"}
{"time":"2022-11-28T14:54:18.561574115Z","level":"INFO","source":"/home/runner/work/kwok/kwok/pkg/kwokctl/cmd/create/cluster/cluster.go:75","msg":"Starting cluster","cluster":"snapshot-cluster-nerdctl-1-23-13"}
time="2022-11-28T14:54:18Z" level=info msg="Creating network kwok-snapshot-cluster-nerdctl-1-23-13"
time="2022-11-28T14:54:18Z" level=warning msg="Ignoring: service kube_apiserver: [Links]"
time="2022-11-28T14:54:18Z" level=warning msg="Ignoring: volume: Bind: [CreateHostPath]"
time="2022-11-28T14:54:18Z" level=warning msg="Ignoring: volume: Bind: [CreateHostPath]"
time="2022-11-28T14:54:18Z" level=warning msg="Ignoring: volume: Bind: [CreateHostPath]"
time="2022-11-28T14:54:18Z" level=warning msg="Ignoring: service kwok_controller: [Links]"
time="2022-11-28T14:54:18Z" level=warning msg="Ignoring: volume: Bind: [CreateHostPath]"
time="2022-11-28T14:54:18Z" level=warning msg="Ignoring: volume: Bind: [CreateHostPath]"
time="2022-11-28T14:54:18Z" level=warning msg="Ignoring: volume: Bind: [CreateHostPath]"
time="2022-11-28T14:54:18Z" level=warning msg="Ignoring: volume: Bind: [CreateHostPath]"
time="2022-11-28T14:54:18Z" level=warning msg="Ignoring: service kube_controller_manager: [Links]"
time="2022-11-28T14:54:18Z" level=warning msg="Ignoring: volume: Bind: [CreateHostPath]"
time="2022-11-28T14:54:18Z" level=warning msg="Ignoring: volume: Bind: [CreateHostPath]"
time="2022-11-28T14:54:18Z" level=warning msg="Ignoring: volume: Bind: [CreateHostPath]"
time="2022-11-28T14:54:18Z" level=warning msg="Ignoring: volume: Bind: [CreateHostPath]"
time="2022-11-28T14:54:18Z" level=warning msg="Ignoring: service kube_scheduler: [Links]"
time="2022-11-28T14:54:18Z" level=warning msg="Ignoring: volume: Bind: [CreateHostPath]"
time="2022-11-28T14:54:18Z" level=warning msg="Ignoring: volume: Bind: [CreateHostPath]"
time="2022-11-28T14:54:18Z" level=warning msg="Ignoring: volume: Bind: [CreateHostPath]"
time="2022-11-28T14:54:18Z" level=warning msg="Ignoring: volume: Bind: [CreateHostPath]"
time="2022-11-28T14:54:18Z" level=info msg="Ensuring image registry.k8s.io/etcd:3.5.6-0"
time="2022-11-28T14:54:18Z" level=info msg="Ensuring image registry.k8s.io/kube-apiserver:v1.23.13"
time="2022-11-28T14:54:18Z" level=info msg="Ensuring image local/kwok:test"
time="2022-11-28T14:54:18Z" level=info msg="Ensuring image registry.k8s.io/kube-controller-manager:v1.23.13"
time="2022-11-28T14:54:18Z" level=info msg="Ensuring image registry.k8s.io/kube-scheduler:v1.23.13"
time="2022-11-28T14:54:18Z" level=info msg="Creating container kwok-snapshot-cluster-nerdctl-1-23-13-kube-scheduler"
time="2022-11-28T14:54:18Z" level=info msg="Creating container kwok-snapshot-cluster-nerdctl-1-23-13-etcd"
time="2022-11-28T14:54:18Z" level=info msg="Creating container kwok-snapshot-cluster-nerdctl-1-23-13-kube-controller-manager"
time="2022-11-28T14:54:18Z" level=info msg="Creating container kwok-snapshot-cluster-nerdctl-1-23-13-kube-apiserver"
time="2022-11-28T14:54:18Z" level=info msg="Creating container kwok-snapshot-cluster-nerdctl-1-23-13-kwok-controller"
You can now use your cluster with:
{"time":"2022-11-28T14:54:22.92009441Z","level":"INFO","source":"/home/runner/work/kwok/kwok/pkg/kwokctl/cmd/create/cluster/cluster.go:75","msg":"Cluster is ready","cluster":"snapshot-cluster-nerdctl-1-23-13"}

    kubectl config use-context kwok-snapshot-cluster-nerdctl-1-23-13

Thanks for using kwok!
No resources found
No resources found
deployment.apps/fake-pod created
node/fake-node created
{"time":"2022-11-28T14:55:00.555011[10](https://github.com/kubernetes-sigs/kwok/actions/runs/3565851048/jobs/5991537840#step:13:11)1Z","level":"ERROR","source":"/opt/hostedtoolcache/go/1.19.3/x64/src/runtime/proc.go:250","msg":"Execute exit","err":"nerdctl cp /home/runner/.kwok/clusters/snapshot-cluster-nerdctl-1-23-13/etcd-data kwok-snapshot-cluster-nerdctl-1-23-13-etcd:/: exit status 1\ntime=\"2022-[11](https://github.com/kubernetes-sigs/kwok/actions/runs/3565851048/jobs/5991537840#step:13:12)-28T14:55:00Z\" level=warning msg=\"failed to inspect NetNS\" error=\"failed to Statfs \\\"/proc/21546/ns/net\\\": no such file or directory\" id=37a024f06534b4c24888948cb02592bfbf348a86def52b0ef420c9b2278c5e95\ntime=\"2022-11-28T14:55:00Z\" level=fatal msg=\"expected container status running, got stopped\"\n"}
Error: Empty snapshot restore failed
Expected: 
Actual: NAMESPACE NAME
default fake-pod-6bf4bdd9cc-5jqlf
NAME
fake-node
{"time":"2022-11-28T14:55:57.588653024Z","level":"INFO","source":"/home/runner/work/kwok/kwok/pkg/kwokctl/cmd/delete/cluster/cluster.go:45","msg":"Stopping cluster","cluster":"snapshot-cluster-nerdctl-1-23-13"}
time="2022-11-28T14:55:57Z" level=info msg="Removing container kwok-snapshot-cluster-nerdctl-1-23-13-kwok-controller"
time="2022-11-28T14:55:57Z" level=info msg="Removing container kwok-snapshot-cluster-nerdctl-1-23-13-kube-scheduler"
time="2022-11-28T14:55:57Z" level=info msg="Removing container kwok-snapshot-cluster-nerdctl-1-23-13-kube-controller-manager"
time="2022-11-28T14:55:58Z" level=info msg="Removing container kwok-snapshot-cluster-nerdctl-1-23-13-kube-apiserver"
time="2022-11-28T14:55:58Z" level=info msg="Removing container kwok-snapshot-cluster-nerdctl-1-23-13-etcd"
time="2022-11-28T14:55:58Z" level=info msg="Removing network kwok-snapshot-cluster-nerdctl-1-23-13"
{"time":"2022-11-28T14:55:58.389470291Z","level":"INFO","source":"/home/runner/work/kwok/kwok/pkg/kwokctl/cmd/delete/cluster/cluster.go:45","msg":"Deleting cluster","cluster":"snapshot-cluster-nerdctl-1-23-13"}
{"time":"2022-11-28T14:55:58.526502308Z","level":"INFO","source":"/home/runner/work/kwok/kwok/pkg/kwokctl/cmd/delete/cluster/cluster.go:45","msg":"Cluster deleted","cluster":"snapshot-cluster-nerdctl-1-23-13"}
------------------------------
Testing snapshot on nerdctl for 1.22.15
{"time":"2022-11-28T14:55:58.545860907Z","level":"INFO","source":"/home/runner/work/kwok/kwok/pkg/kwokctl/cmd/create/cluster/cluster.go:75","msg":"Creating cluster","cluster":"snapshot-cluster-nerdctl-1-22-15"}
{"time":"2022-11-28T14:55:59.42[12](https://github.com/kubernetes-sigs/kwok/actions/runs/3565851048/jobs/5991537840#step:13:13)21125Z","level":"INFO","source":"/home/runner/work/kwok/kwok/pkg/kwokctl/cmd/create/cluster/cluster.go:75","msg":"Starting cluster","cluster":"snapshot-cluster-nerdctl-1-22-15"}
time="2022-11-28T[14](https://github.com/kubernetes-sigs/kwok/actions/runs/3565851048/jobs/5991537840#step:13:15):55:59Z" level=info msg="Creating network kwok-snapshot-cluster-nerdctl-1-22-[15](https://github.com/kubernetes-sigs/kwok/actions/runs/3565851048/jobs/5991537840#step:13:16)"
time="2022-11-28T14:55:59Z" level=warning msg="Ignoring: service kube_apiserver: [Links]"
time="2022-11-28T14:55:59Z" level=warning msg="Ignoring: volume: Bind: [CreateHostPath]"
time="2022-11-28T14:55:59Z" level=warning msg="Ignoring: volume: Bind: [CreateHostPath]"
time="2022-11-28T14:55:59Z" level=warning msg="Ignoring: volume: Bind: [CreateHostPath]"
time="2022-11-28T14:55:59Z" level=warning msg="Ignoring: service kube_controller_manager: [Links]"
time="2022-11-28T14:55:59Z" level=warning msg="Ignoring: volume: Bind: [CreateHostPath]"
time="2022-11-28T14:55:59Z" level=warning msg="Ignoring: volume: Bind: [CreateHostPath]"
time="2022-11-28T14:55:59Z" level=warning msg="Ignoring: volume: Bind: [CreateHostPath]"
time="2022-11-28T14:55:59Z" level=warning msg="Ignoring: volume: Bind: [CreateHostPath]"
time="2022-11-28T14:55:59Z" level=warning msg="Ignoring: service kube_scheduler: [Links]"
time="2022-11-28T14:55:59Z" level=warning msg="Ignoring: volume: Bind: [CreateHostPath]"
time="2022-11-28T14:55:59Z" level=warning msg="Ignoring: volume: Bind: [CreateHostPath]"
time="2022-11-28T14:55:59Z" level=warning msg="Ignoring: volume: Bind: [CreateHostPath]"
time="2022-11-28T14:55:59Z" level=warning msg="Ignoring: volume: Bind: [CreateHostPath]"
time="2022-11-28T14:55:59Z" level=warning msg="Ignoring: service kwok_controller: [Links]"
time="2022-11-28T14:55:59Z" level=warning msg="Ignoring: volume: Bind: [CreateHostPath]"
time="2022-11-28T14:55:59Z" level=warning msg="Ignoring: volume: Bind: [CreateHostPath]"
time="2022-11-28T14:55:59Z" level=warning msg="Ignoring: volume: Bind: [CreateHostPath]"
time="2022-11-28T14:55:59Z" level=warning msg="Ignoring: volume: Bind: [CreateHostPath]"
time="2022-11-28T14:55:59Z" level=info msg="Ensuring image registry.k8s.io/etcd:3.5.6-0"
time="2022-11-28T14:55:59Z" level=info msg="Ensuring image registry.k8s.io/kube-apiserver:v1.22.15"
time="2022-11-28T14:55:59Z" level=info msg="Ensuring image registry.k8s.io/kube-controller-manager:v1.22.15"
time="2022-11-28T14:55:59Z" level=info msg="Ensuring image registry.k8s.io/kube-scheduler:v1.22.15"
time="2022-11-28T14:55:59Z" level=info msg="Ensuring image local/kwok:test"
time="2022-11-28T14:55:59Z" level=info msg="Creating container kwok-snapshot-cluster-nerdctl-1-22-15-kube-controller-manager"
time="2022-11-28T14:55:59Z" level=info msg="Creating container kwok-snapshot-cluster-nerdctl-1-22-15-kwok-controller"
time="2022-11-28T14:55:59Z" level=info msg="Creating container kwok-snapshot-cluster-nerdctl-1-22-15-kube-scheduler"
time="2022-11-28T14:55:59Z" level=info msg="Creating container kwok-snapshot-cluster-nerdctl-1-22-15-etcd"
time="2022-11-28T14:55:59Z" level=info msg="Creating container kwok-snapshot-cluster-nerdctl-1-22-15-kube-apiserver"
You can now use your cluster with:

    kubectl config use-context kwok-snapshot-cluster-nerdctl-1-22-15

Thanks for using kwok!
{"time":"2022-11-28T14:56:03.6658[16](https://github.com/kubernetes-sigs/kwok/actions/runs/3565851048/jobs/5991537840#step:13:17)766Z","level":"INFO","source":"/home/runner/work/kwok/kwok/pkg/kwokctl/cmd/create/cluster/cluster.go:75","msg":"Cluster is ready","cluster":"snapshot-cluster-nerdctl-1-22-15"}
No resources found
No resources found
deployment.apps/fake-pod created
node/fake-node created
{"time":"2022-11-28T14:56:41.2365[17](https://github.com/kubernetes-sigs/kwok/actions/runs/3565851048/jobs/5991537840#step:13:18)354Z","level":"ERROR","source":"/opt/hostedtoolcache/go/1.[19](https://github.com/kubernetes-sigs/kwok/actions/runs/3565851048/jobs/5991537840#step:13:20).3/x64/src/runtime/proc.go:250","msg":"Execute exit","err":"nerdctl cp /home/runner/.kwok/clusters/snapshot-cluster-nerdctl-1-22-15/etcd-data kwok-snapshot-cluster-nerdctl-1-22-15-etcd:/: exit status 1\ntime=\"[20](https://github.com/kubernetes-sigs/kwok/actions/runs/3565851048/jobs/5991537840#step:13:21)[22](https://github.com/kubernetes-sigs/kwok/actions/runs/3565851048/jobs/5991537840#step:13:23)-11-28T14:56:40Z\" level=warning msg=\"failed to inspect NetNS\" error=\"failed to Statfs \\\"/proc/25054/ns/net\\\": no such file or directory\" id=8ec[23](https://github.com/kubernetes-sigs/kwok/actions/runs/3565851048/jobs/5991537840#step:13:24)8fa41f2f3a7039bf6e120f2de73ad776cc8c775db43b3301157aa430f[26](https://github.com/kubernetes-sigs/kwok/actions/runs/3565851048/jobs/5991537840#step:13:27)\ntime=\"2022-11-[28](https://github.com/kubernetes-sigs/kwok/actions/runs/3565851048/jobs/5991537840#step:13:29)T14:56:[40](https://github.com/kubernetes-sigs/kwok/actions/runs/3565851048/jobs/5991537840#step:13:41)Z\" level=fatal msg=\"expected container status running, got stopped\"\n"}
```

### Since when has it been failing?

Always

### Reason for failure (if possible)

_No response_

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by wzshiming**
#### What type of PR is this?

/kind bug

#### Which issue(s) this PR fixes:

Fixes #100

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: pkg/kwokctl/runtime/compose/cluster_snapshot.go [hunk 1]
```diff
@@ -93,10 +82,58 @@ func (c *Cluster) SnapshotRestore(ctx context.Context, path string) error {
...
+		}()
+
+		// Copy to container from host temporary directory
+		err = exec.Exec(ctx, "", exec.IOStreams{}, conf.Runtime, "cp", etcdDataTmp, etcdContainerName+":/")
+		if err != nil {
+			return err
+		}
+	} else {
+		// TODO: remove this when `nerdctl cp` supports work on stopped containers
+		// https://github.com/containerd/nerdctl/issues/1812
```
Comment (wzshiming) [inline pkg/kwokctl/runtime/compose/cluster_snapshot.go:105]: https://github.com/containerd/nerdctl/issues/1812
