### PR TITLE
Fix SC2002 for shellcheck

### LINKED ISSUE #470: ☂️ Code Cleanup for shell
https://www.shellcheck.net/wiki/

## Tasks

- [X] SC2002 #492
- [x] SC2009 #498
- [x] SC2015 #521
- [X] SC2034 #491
- [x] SC2038 #500
- [x] SC2046  #554
- [x] SC2053 #496
- [x] SC2069 #504
- [x] SC2076 #546
- [x] SC2086 #519
- [x] SC2155 #501
- [x] SC2126 #497
- [x] SC2181 #560
- [x] SC2207 #561
- [X] SC2294 #493

### Install shellcheck

https://github.com/koalaman/shellcheck#installing

On macOS (OS X) with Homebrew:

```shell
brew install shellcheck
```

### Remove the rule you want to cleanup

https://github.com/kubernetes-sigs/kwok/blob/main/hack/verify-shellcheck.sh#L36

### Check

Run the following based on root of this repo:

```shell
./hack/verify-shellcheck.sh 
```

### Clean up
Clean up the code based on the error reported by the check

## Example

PR:
- #491
- #492
- #493

### PR DESCRIPTION
**Pull request by Zhuzhenghao**
#### What type of PR is this?

/kind cleanup

#### Which issue(s) this PR fixes:

xref #470

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: test/kwokctl/helper.sh [hunk 1]
```diff
@@ -46,7 +46,7 @@ function test_all() {
 LAST_RELEASE_SIZE="${LAST_RELEASE_SIZE:-1}"
 
 function supported_releases() {
-  cat "${ROOT_DIR}/supported_releases.txt" | head -n "${LAST_RELEASE_SIZE}"
+  head <"${ROOT_DIR}/supported_releases.txt" -n "${LAST_RELEASE_SIZE}"
```
Comment (wzshiming) [inline test/kwokctl/helper.sh:49]:
```suggestion
  < "${ROOT_DIR}/supported_releases.txt" head -n "${LAST_RELEASE_SIZE}"
```

File: test/kwokctl/kwokctl_logs_test.sh [hunk 2]
```diff
@@ -65,7 +65,7 @@ function test_logs() {
       return 1
   fi
 
-  local want=$(cat "${targetLog}" | cut -d " " -f 4-)
+  local want=$(cut <"${targetLog}" -d " " -f 4-)
```
Comment (wzshiming) [inline test/kwokctl/kwokctl_logs_test.sh:68]:
```suggestion
  local want=$(< "${targetLog}" cut -d " " -f 4-)
```

File: test/kwokctl/kwokctl_logs_test.sh [hunk 3]
```diff
@@ -80,7 +80,7 @@ function test_logs() {
       return 1
   fi
 
-  local want=$(cat "${targetLog}" | tail -n 2 | cut -d " " -f 4-)
+  local want=$(tail <"${targetLog}" -n 2 | cut -d " " -f 4-)
```
Comment (wzshiming) [inline test/kwokctl/kwokctl_logs_test.sh:83]:
```suggestion
  local want=$(< "${targetLog}" tail -n 2 | cut -d " " -f 4-)
```

File: test/kwokctl/kwokctl_logs_test.sh [hunk 4]
```diff
@@ -95,7 +95,7 @@ function test_logs() {
...
```
Comment (wzshiming) [inline test/kwokctl/kwokctl_logs_test.sh:98]:
```suggestion
  local want=$(< "${targetLog}" tail -n 2 | cut -d " " -f 4-)
```

File: test/kwokctl/kwokctl_logs_test.sh [hunk 5]
```diff
@@ -111,7 +111,7 @@ function test_logs() {
   sleep 5
   kill -INT "${pid}"
 
-  local want=$(cat "${targetLog}" | cut -d " " -f 4-)
+  local want=$(cut <"${targetLog}" -d " " -f 4-)
```
Comment (wzshiming) [inline test/kwokctl/kwokctl_logs_test.sh:114]:
```suggestion
  local want=$(< "${targetLog}" cut -d " " -f 4-)
```

**Review by wzshiming — APPROVED** [review]
/approve
/lgtm
